# Generated by Django 3.0.3 on 2020-07-05 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
